name: Publish Github Pages Sphinx

on:
  push:
    branches: [sphinx-actions]
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U sphinx sphinx-intl sphinx-rtd-theme sphinxcontrib-openapi
        sphinx-apidoc -o docs geonode_provider/
